### ISSUE TITLE
Consider adding a Twitter hashtag box

### ISSUE THREAD

**Issue by cordawso** [Solomonabo/wp-content#10]
Since this is a news site, it would be good to add some live news about Africa from Twitter. [Here are some instructions](https://www.sociablekit.com/embed-twitter-hashtag-feed-on-website/) on how to create and embed a timeline based on a hashtag. For example, you could find the #africanews feed and embed that.

**Comment by Solomonabo** [comment]
Fantastic! thanks so much, the socialblekit.com is a great resource.

**Comment by greglinch** [comment]
I'd recommend using an embed that pulls from a trusted Twitter list or favorites instead of a hashtag. Otherwise you could get some pretty awful or spammy things that might appear on the hashtag.

**Comment by Solomonabo** [comment]
Many thanks fr the heads up.
