### ISSUE TITLE
fix menu click when viewing site on smaller screens

### ISSUE THREAD

**Issue by greglinch** [Solomonabo/wp-content#18]
Currently nothing happens (e.g. it doesn't expand) when I click on the menu on a smaller screen size:

<img width="272" alt="Screen Shot 2019-04-24 at 10 18 27 PM" src="https://user-images.githubusercontent.com/327783/56705469-fd4d8680-66de-11e9-8bb8-b639001f6e5b.png">

**Comment by greglinch** [comment]
Overall, everything else looked and worked as expected on a small screen. Well done there!

**Comment by Solomonabo** [comment]
Used WPtouch plugin to correct this anomaly. Many thanks for the feedback
