### ISSUE TITLE
add customizations related to taxonomy

### ISSUE THREAD

**Issue by greglinch** [Solomonabo/wp-content#19]
In your presentation you mentioned a taxonomy of countries and topics. Those could count as one or two code customizations in the form of separate plugins. Your site could use those additional coded pieces for more customization credit.

**Comment by greglinch** [comment]
One idea could be to add a custom post type for Clips with custom taxonomy for publication (like a category).

**Comment by greglinch** [comment]
Removed the second comment because it was added to the wrong repo.

**Comment by Solomonabo** [comment]
Just created the countries taxonomies. I created parent  five country taxonomy  with some of their respective child countries. For example East Africa has Kenya as child, West Africa has Ghana, North Africa, Egypt among other. I will update all the corresponding countries subsequently.

Many thanks

**Comment by greglinch** [comment]
@Solomonabo Thanks. I just updated your grade to reflect the changes.
