### ISSUE TITLE
higher res header

### ISSUE THREAD

**Issue by cgpriceisright** [Solomonabo/wp-content#21]
really like the header image concept. I saw a few issues also suggesting you update. but ill go a step further and recommend (if this website gets off the ground and in the direction of a news site with a larger staff), you pursue a service like AP images or Getty. they have subscription based high quality photos for news orgs

**Comment by Solomonabo** [comment]
Yes, the quality of the image I used is so terrible, some people have suggested other sites for free but high resolution images, but like you said nothing can beat Getty's images
