### ISSUE TITLE
breaking news banner

### ISSUE THREAD

**Issue by cgpriceisright** [Solomonabo/wp-content#22]
I'd push the banner to the top of the page rather than below the header image. that's the style for POLITICO and a lot of news orgs, and it works pretty well because the header is often the most well known/remembered, and sacrificing real estate there is not as detrimental compared to distracting from menu content

**Comment by Solomonabo** [comment]
That sounds so great, just checked politics's website and will definitely tweak it. Really appreciate the feedback man.
