### ISSUE TITLE
Update header image

### ISSUE THREAD

**Issue by szs10** [Solomonabo/wp-content#3]
I really like your choice for the header. It underlines the feeling of the website, flows with the content. What I would recommend doing is finding a higher quality image - the website I usually use for this is [Unsplash](https://unsplash.com), you should check it out!

**Comment by greglinch** [comment]
I agree. This is the first things visitors see when they come to your site and is key to the first impression (and who doesn't love elephants!). Other possible images sources include Flickr or Google Image search — just be sure to filter by the correct rights/usage allowed.

**Comment by Solomonabo** [comment]
Great, I realize the image quality was terrible, and yes Greg, there are people who won't like elephants like I do. Many thanks Szs10, I will browse through Unsplash to find good image.
