### ISSUE TITLE
Edit Current Page Link

### ISSUE THREAD

**Issue by sidlowsh** [Solomonabo/wp-content#5]
In the main menu, the link color for the current page is hard to read (it's a dark grey on another gray menu bar). Consider changing the current link color to white or red to match the theme while making it easier to read. 
To do this, change the a:active or a:visited CSS tags.

Link: https://stackoverflow.com/questions/2397370/change-link-color-of-the-current-page-with-css

**Comment by Solomonabo** [comment]
Awesome Sarah. many thanks
