### ISSUE TITLE
Visual Appeal

### ISSUE THREAD

**Issue by szs10** [Solomonabo/wp-content#8]
Even though your website is coherent and easy to follow, try adding more images and a little change in fonts and styling. It would definitely help in grabbing the visitor's attention and make him or her want to stay longer on your website!

**Comment by lexinal** [comment]
I feel like this could be even more of a powerful website, but there are a few elements that can be distracting. I would consider changing the grey color on the bottom and maybe searching a lighter red to not be so harsh on the eyes.

**Comment by Solomonabo** [comment]
Great suggestions, you guys are the best.
