### ISSUE TITLE
Consider altering your page size to change the width

### ISSUE THREAD

**Issue by cordawso** [Solomonabo/wp-content#9]
The width of the site makes text stretch all the way across the page. You might want to try to do this by calling the .page ID and altering the width, however that would likely alter the width of the photos as well. Be sure to make the width dynamic so it changes with the size of a browser.

**Comment by Solomonabo** [comment]
OK, was wondering how to do that, but will research and work on it. Thanks for the great feedback man, I really appreciate it.
